### ISSUE TITLE
Phone number regex in ModerationCtrl is too greedy

### ISSUE THREAD

**Issue by jkeat** [UPchieve/server#389]
We've had a few reports of numbers that aren't phone numbers being blocked by the moderation filter. e.g.

> I tried to send this message:
> (which is actually 0.001193067%)
> and got this error:
> Messages cannot contain personal information or profanity

Current pattern in ModerationCtrl:
`const PHONE_REGEX = /(\(?\d{3}\)?[-. ]?)?\d{3}[-. ]?\d{4}/g`

This regex pattern is too greedy -- we should use something like https://stackoverflow.com/a/16699507

**Comment by ti2ger92** [comment]
IMHO, the selected pattern: `^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$` isn't quite greedy enough, because it requires the line to start and end with the phone number. I'd remove that, but add the requirement [the area code first digit range is 2-9](https://en.wikipedia.org/wiki/North_American_Numbering_Plan#Modern_plan)

**Comment by jkeat** [comment]
Resolved by https://github.com/UPchieve/server/pull/418
